### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by KangJiYoung** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#12]
I am trying to update database and I get this error(its the first migration):
`System.NullReferenceException: Object reference not set to an instance of an object.    at MySQL.Data.Entity.Migrations.MySQLHistoryRepository.get_ExistsSql()
    at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
    at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0() 
    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
    at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args) 
 Object reference not set to an instance of an object.`

**Comment by SapientGuardian** [comment]
This should be fixed in 7.1.5, please re-open this issue if it is not.

**Comment by kunyx** [comment]
> dotnet ef database update
> is my first migration and getting this error:
> Project DomainModel (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
> Project DataAccessMySqlProvider (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
> Project kunyx_rest-api (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at MySQL.Data.Entity.Migrations.MySQLHistoryRepository.get_ExistsSql()
>    at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
>    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
>    at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
>    at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
>    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
> Object reference not set to an instance of an object.

**Comment by SapientGuardian** [comment]
@kunyx can you please check your project.json.lock file and let us know what version of the library it has listed?

**Comment by kunyx** [comment]
"MySql.Data.EntityFrameworkCore": "7.0.6-IR31"

**Comment by kunyx** [comment]
"SapientGuardian.MySql.Data": "6.9.812"
"SapientGuardian.EntityFrameworkCore.MySql": "7.1.4"

**Comment by kunyx** [comment]
"Microsoft.EntityFrameworkCore": "1.0.0"

**Comment by kunyx** [comment]
Is v 7.1.5 available?

**Comment by SapientGuardian** [comment]
The latest is [7.1.12](https://www.nuget.org/packages/SapientGuardian.EntityFrameworkCore.MySql/7.1.12). That should fix this and a number of other bugs. You mentioned that you're also referencing the official MySQL EF Core provider; you might see some strange behavior having both in the same project. Not sure why you would want that.

**Comment by kunyx** [comment]
Thanks Noah,
I am using version 7.1.12 now. It is much better and strange behavior could
be of official MySQL EF Core provider but this is the new area for me.

2016-11-05 11:25 GMT+00:00 Noah Potash notifications@github.com:
