### ISSUE TITLE
Update-Database fails with SQL default value specified

### ISSUE THREAD

**Issue by jeffbromberger** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#23]
I am trying to define columns that are equivalent to this:

    `CreatedTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `LastActiveTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,

I have these annotations:

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(TypeName = "datetime")]
        public DateTime CreatedTime { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(TypeName = "datetime")]
        public DateTime LastActiveTime { get; set; }

And in OnModelCreating I have this:

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Client>()
                .Property(p => p.RowVersion)
                .IsRequired(true)
                .HasDefaultValue((long)1);

            modelBuilder.Entity<Client>()
                .Property(p => p.CreatedTime)
                .IsRequired(true)
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            modelBuilder.Entity<Client>()
                .Property(p => p.LastActiveTime)
                .IsRequired(true)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
        }

But when I run Update-Database it gives the following error and seems to be referencing an issue with the CURRENT_TIMESTAMP value.  I don't know how to debug this any further, is there a way to get more details on what it is upset about?  Or do you see what is wrong in my code?

PM> Update-Database
MySql.Data.MySqlClient.MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(CURRENT_TIMESTAMP),     `Description` varchar(255),
    `Hostname` varchar(25' at line 5
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
    at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection) 
    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection) 
    at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection) 
    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
    at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
    at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0() 
    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) 
    at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args) 
 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(CURRENT_TIMESTAMP), 
    `Description` varchar(255),
    `Hostname` varchar(25' at line 5

**Comment by jeffbromberger** [comment]
@SapientGuardian

**Comment by SapientGuardian** [comment]
What version of MySQL are you running? I was able to reproduce your problem, but I'm running 5.5 and the ability to set the default of datetime to a function wasn't introduced until 5.6 (http://dev.mysql.com/doc/refman/5.6/en/timestamp-initialization.html)

Here's the generated SQL, which looks valid to me (except for using a DB feature that I don't have)

```
 CREATE TABLE `Client` (
          `uuid` CHAR(36) NOT NULL,
          `CreatedTime` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
          `LastActiveTime` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
          `RowVersion` bigint NOT NULL DEFAULT 1 AUTO_INCREMENT,
          PRIMARY KEY (`uuid`)
      );
```

**Comment by jeffbromberger** [comment]
I'm running 5.7.  It looks like the problem is the parentheses.  If I take your statement and execute it in workbench as-is it fails due to syntax.  If I remove the ( ) then it works.  Is it possible to just have HasDefaultValueSql() use the string verbatim?  If some use case would require parens then the dev could insert them, but if they are added automatically you can't possibly remove them.

**Comment by SapientGuardian** [comment]
Seems reasonable, I've just put in a PR to fix it.

**Comment by SapientGuardian** [comment]
This should be fixed in version 7.1.12, which will hit the feeds in a few minutes.

**Comment by jeffbromberger** [comment]
Awesome, thank you! 

Is this one fixed in that release as well?   https://github.com/aspnet/EntityFramework/issues/6914#issuecomment-258067081

**Comment by SapientGuardian** [comment]
My understanding is that it should simply work if you rebuild this library against 1.1.0-preview1-final, but I don't want to update our official package to reference a preview version. It sounds like they're going to revert the break, so if they publish another preview with it fixed, you should be able to use that. Otherwise, you'll have to wait until the final release of EF, at which time I'll bump the dependency here.

**Comment by jeffbromberger** [comment]
Re-reading it now it sounds like you are right.  I'm still on EF 1.0 for now so it's not a blocker.  Thanks again for the quick fix on the default value stuff, it works perfectly now.
