### ISSUE TITLE
OnDelete defaulting to cascade but should be restrict

### ISSUE THREAD

**Issue by jeffbromberger** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#26]
Per this:

https://stackoverflow.com/questions/36010867/entity-framework-parent-child-linking-and-foreign-key-constrain-failed-error

The default behavior for referential delete should be "restrict" but when I don't specify anything it is specifying cascade.

Thoughts?

**Comment by jeffbromberger** [comment]
But this almost seems to contradict that as to what the default should be:

http://stackoverflow.com/questions/33807879/ef7-rc1-disable-cascade-delete

**Comment by SapientGuardian** [comment]
My interpretation of those two threads is that the default for _required_ relationships is cascade, but for non-required is restrict. I don't see anything in our codebase that deals with this specifically, so whatever the behavior is, I think it's baked into EF.

**Comment by jeffbromberger** [comment]
Ok, thanks for checking it out.  In my case you could delete every row in all 5 tables in my database just by deleting 1 row in the top parent.  Seems like restrict would be a much safer default, but what do I know!
