### ISSUE TITLE
doubles are getting declared as floats

### ISSUE THREAD

**Issue by jeffbromberger** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#27]
Really hope I'm not wasting your time again :)

I have a class which has fields declared as follows:

        public double Latitude { get; set; }
        public double Longitude { get; set; }

In the generated migration file I see the following:

         Latitude = table.Column<double>(nullable: false),
         Longitude = table.Column<double>(nullable: false),

But when I look at the SQL being used to create the table, it is:

    `Latitude` float NOT NULL,
    `Longitude` float NOT NULL,

Do I need to do something extra to force these to be doubles or is this a bug?

**Comment by SapientGuardian** [comment]
It's a bug. Will be fixed shortly.

**Comment by SapientGuardian** [comment]
Fixed in 7.1.13, just hit the feed.

**Comment by jeffbromberger** [comment]
Thank you!
