### ISSUE TITLE
Encoding utf-8 latin1

### ISSUE THREAD

**Issue by kleberksms** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#48]
Im doing a sql query with EF Core, but my encodig return wrong,
https://stackoverflow.com/questions/42162182/encoding-mysql-ef-core
Databse settings:

    charset: latin1
    collation: latin1_general_ci

Database - engine InnoDb - charset: latin1 - collation: latin1_general_ci

This is a MySql Db

https://i.stack.imgur.com/sGBH1.png

https://i.stack.imgur.com/inh89.png

Repository

    public Repository(CrmGatewayCarteirasContext context)
    {
        Context = context;
        DbSet = context.Set<TEntity>();
    }

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    public IEnumerable<TEntity> GetAll()
    {
        return DbSet.ToList();
    }

    protected virtual void Dispose(bool disposing)
    {
        if (_disposed) return;
        _disposed = true;
    }

project.json

{
"dependencies": {
    "Microsoft.NETCore.App": {
        "version": "1.1.0",
        "type": "platform"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Serilog.Extensions.Logging": "1.3.1",
    "Serilog.Sinks.RollingFile": "3.3.0",
    "Serilog.Exceptions": "2.3.0",
    "Seq.Extensions.Logging": "2.1.1",
    "Serilog.Sinks.Seq": "3.2.0",
    "Microsoft.EntityFrameworkCore.Design": {
        "type": "build",
        "version": "1.1.0"
    },
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "AutoMapper": "5.2.0",
    "AutoMapper.Extensions.Microsoft.DependencyInjection": "1.2.0",
    "CrmGateway.SharedKernel": "1.0.0-*",
    "Microsoft.ApplicationInsights.AspNetCore": "2.0.0",
    "Microsoft.AspNetCore.Mvc": "1.1.1",
    "SapientGuardian.EntityFrameworkCore.MySql": "7.1.18",
    "StaticCommons": "1.4.0"
},
"tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-final",
    "Microsoft.EntityFrameworkCore.Tools": {
        "version": "1.1.0-preview4-final",
        "imports": [
            "portable-net45+win8+dnxcore50",
            "portable-net45+win8"
        ]
    }
}}

**Comment by eByte23** [comment]
Not sure why your getting this but possibly try adding the encoding type you require to the end of your connection string e.g. ';Charset=utf8'

**Comment by kleberksms** [comment]
@eByte23 , I changed, but return same result. =/

**Comment by eByte23** [comment]
Is this coming from a web input model by any chance? Have you tried with a unit test inserting exact data I just wonder if before ot gets to db it's already wrong?

**Comment by eByte23** [comment]
Sorry disregard last, I see its in the database correct but when querying with entity is incorrect?

I'll do some tests when I get home

**Comment by kleberksms** [comment]
The first version this code was in Azure, I no have problems with encoding.
I not tested with SqlServer, but in Mysql I still have this error.

this error start before _context.Model.Find ();

**Comment by SapientGuardian** [comment]
Your fix has been included in version 7.1.20

**Comment by kleberksms** [comment]
sorry for the bad english...

Wrong dependency yet
![dependencies](https://cloud.githubusercontent.com/assets/3289590/23919184/a59ecc9c-08d4-11e7-9a45-e056a6c9d555.png)

**Comment by SapientGuardian** [comment]
You are correct, nice catch. Try 7.1.21

**Comment by kleberksms** [comment]
Tnks
