### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by GuerrillaCoder** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#5]
Hi,

I am trying to get MySQL working with asp.net entity framework core and found your project.

How do I add this to the db content?

The core docs show an example for the mssql provider:

```
services.AddDbContext<DbContext>(options => options.UseSqlServer(connection));
```

How do I do this with your MySQL data provider?

I tried adding to see if any new methods appeared:

```
using SapientGuardian.EntityFrameworkCore.Mysql;
```

But it is not recognizing the namespace.  Can you tell me how to configure it please?

**Comment by SapientGuardian** [comment]
Hello,

The correct namespace is actually `MySQL.Data.Entity.Extensions`. After you add that, you should have the UseMySQL extension method. Here's an example: https://github.com/SapientGuardian/AspNet5MultipleProject/blob/master/src/AspNet5MultipleProject/Startup.cs#L76

**Comment by GuerrillaCoder** [comment]
Cool thanks, now the method appears :)
