### ISSUE TITLE
Boolean values not working

### ISSUE THREAD

**Issue by Inrego** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#54]
The following code is generated in the migration:

    migrationBuilder.AddColumn<bool>(
        name: "Visible",
        table: "mediafile",
        nullable: false,
        defaultValue: false);

This looks fine.
But the generated sql looks like this: 

    ALTER TABLE `mediafile` ADD `Visible` bit NOT NULL DEFAULT 'False';

The default value is wrong. It should be `0`. I've tried setting the default value to 0 in the migration file, but it is still put into a string, which gives an error saying `Invalid default value for 'Visible'`

The correct sql should be: 

    ALTER TABLE `mediafile` ADD `Visible` bit NOT NULL DEFAULT 0;

Or possibly even using the column type `BOOLEAN` instead of `BIT`:

    ALTER TABLE `mediafile` ADD `Visible` BOOLEAN NOT NULL DEFAULT FALSE

**Comment by nezbo** [comment]
I am blocked by the above issue too. Is there a workaround or a fix coming soon?

**Comment by Inrego** [comment]
I didn't find any *good* workarounds, but I did manage to work my way around it. Simply by removing creation of that column from the migration upgrade code. And then I added the column manually in the database.

**Comment by nezbo** [comment]
That is indeed not a good workaround, but might be the only one for now. I hope this gets resolved soon.

**Comment by SapientGuardian** [comment]
Fixed in 7.1.23, which will be published shortly.
