### ISSUE TITLE
MethodAccessException when start debugging

### ISSUE THREAD

**Issue by SilverioMiranda** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#58]
When i try to start debbug in visual studio 2017 i get this exception :

![image](https://cloud.githubusercontent.com/assets/1939153/24826139/7f60ee72-1c05-11e7-8519-48db9d895b2b.png)

I can run this project using dotnet run or dotnet watch run in both netcore 1.1 and net46

What details i need to add here?

**Comment by SapientGuardian** [comment]
You're using an old version of the libraries, you should be on SapientGuardian.EntityFrameworkCore.MySql  7.1.23 and  SapientGuardian.MySql.Data 6.9.816 (which is a dependency of 7.1.23, but you could be overriding it).

**Comment by SilverioMiranda** [comment]
Thanks
