### ISSUE TITLE
Issue with using Limit and Skip

### ISSUE THREAD

**Issue by zenoware** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#7]
When attempting to apply limit and skip on a query, the following error occurs:

At least one object must implement IComparable.

Here is an example

```
DbSet<TempModel> dbSet = dbContext.Set<TempModel>();
dbSet.AsQueryable().Skip(0).Limit(10);
```

```
TempModel could be something like this:
public class TempModel {
public int Id {get;set;}
public double Value {get;set;}
}
```

Now, in my model, I am referencing other models so not sure if that may cause some issues or not. I am including those tables on the dbSet if I reference them.

**Comment by zenoware** [comment]
Note, the error above is actually not from Limit or Skip, but with OrderBy.  If I remove the OrderBy, then I get the following error which is directly related to Limit and Skip:

Undeclared variable: __p_1

**Comment by SapientGuardian** [comment]
Your example didn't include the OrderBy, what did you have for that clause?

**Comment by how02** [comment]
Looks like MySQL.Data.Entity.Query.MySQLQuerySqlGenerator.GenerateLimitOffset isn't implemented properly.
Creating a pull request now.

**Comment by zenoware** [comment]
I pulled down the source from github for both MySql.Data and SapientGuardian.EntityFrameworkCore.MySql.

So, when calling just Limit or Skip, the query command string ends with LIMIT __p_1 (line 138 in MySql.Data.MySqlClient.MySqlCommand).

When I added the OrderBy, it does not add anything to the actual cmmand string.

So here is a more elaborative example:

Given this Model:

```
public class Expense
    {
        public int Id { get; set; }
        public ExpenseCode ExpenseCode { get; set; }
        public SubOrganization SubOrganization { get; set; }
        public double Total { get; set; }
        public DateTime PurchaseDate { get; set; }
        public Department Department { get; set; }
        public byte[] RecieptFile { get; set; }
        public DateTime CreatedDate { get; set; }
        public string Description { get; set; }
        public ApplicationUser CreatedBy { get; set; }
    }
```

And this query (granted, I am using dependency injection and a repository pattern so I will skip all that for now and go as if I am doing the using pattern for the context):

```
using(DbContext context = new DbContext(<connection info>)){
  var query = context.Expenses.Skip(0).Limit(10);
} 
```

I will get the **Undeclared variable: __p_1** because that is what is in the command string.

So when I am trying to apply an Order, it is something along these lines:

```
using(DbContext context = new DbContext(<connection info>)){
  var query = context.Expenses.OrderBy(e => e.Total).Skip(0).Limit(10);
} 
```

When this is called, I get the error **At least one object must implement IComparable.**

Hopefully that may help clarify the issue.

Thanks for being so quick at checking this out!

**Comment by SapientGuardian** [comment]
The fix for the limit issue has been published as version 7.1.2. Sounds like there might be a separate issue with the OrderBy though, right @how02?

**Comment by how02** [comment]
I'm not able to reproduce the issue with OrderBy.

**Comment by SapientGuardian** [comment]
@Zenoware In your example, e.Total is a double, which is very much comparable. Are you ordering by a double in your actual code, or are you perhaps ordering by an object (which, if it doesn't implement IComparable, would rightfully throw that exception)?

**Comment by zenoware** [comment]
It is possible I am ordering by a field that isn't comparable.  Let me run my code and check it out.  Since I am using DataTables and an Ajax call back to my service layer, it is possible it is trying to order by something weird like a base64 image or something.

**Comment by zenoware** [comment]
@SapientGuardian that was it for the order and it did appear that is what was messing me up the whole time... Now I feel a bit silly :(  Thanks for the help!  Also seemed that I was pulling 7.1.1 from nuget but fixed that problem and the limit/skip issue was also resolved.  Thanks!
